### ISSUE TITLE
RSI example fails R CMD check

### ISSUE THREAD

**Issue by joshuaulrich** [joshuaulrich/TTR#101]
The RSI example below fails R CMD check in recent R-devel because it throws a warning.

```r
> # Case of two different 'maType's for both MAs
> rsiMA2 <- RSI(price, n=14, maType=list(maUp=list(EMA,ratio=1/5),
+ maDown=list(WMA,wts=1:10)))
Warning in formals(fun) : argument is not a function
```

**Comment by thistleknot** [comment]
What's the fix?

**Comment by thistleknot** [comment]
nevermind: https://github.com/joshuaulrich/TTR/commit/130006abdaa041d4b8cc60a36533b8a03739e9f2

**Comment by thistleknot** [comment]
I was trying to use your provided example in my code and even with the latest dev it still throws the same error, but I see in your comment that you plan on amending the example..

**Comment by thistleknot** [comment]
rsiMA2 <- RSI(data$Adjusted, n=14, maType=list(maUp=list(EMA),maDown=list(WMA,wts=data$Volume)))

**Comment by joshuaulrich** [comment]
Not sure what the problem is for you. Your example works for me with the latest on CRAN:

```r
library(TTR)
data(ttrc)
rsiMA2 <- RSI(ttrc$Close, n=14, maType=list(maUp=list(EMA),maDown=list(WMA,wts=ttrc$Volume)))
tail(rsiMA2)
## [1] 59.40398 51.07850 51.10025 58.22955 57.62683 51.57147
packageVersion("TTR")
## [1] '0.24.2'
```

**Comment by thistleknot** [comment]
I was just offering it as a working example.  Thinks are good for me on my end now.  I think the update did it?  I'm not sure.
