### ISSUE TITLE
Issue with marketcap?

### ISSUE THREAD

**Issue by ahdee** [joshuaulrich/TTR#109]
### Description
Hi 
TTR::stockSymbols() can still retrieves the symbols however market cap are all NA. Does anyone have an issue? 

version is TTR_0.24.2  
R version 4.0.3 (2020-10-10)

thanks. 

Alex

**Comment by joshuaulrich** [comment]
It's no longer available. See #98 and 2199dd838aa7ff62291da9fb30ae3ee76c5ac446.
