### ISSUE TITLE
how can i buy and finish a operation in R?

### ISSUE THREAD

**Issue by igorpw4** [joshuaulrich/TTR#119]
### Description
How can i buy when rsi(2) are under 25 and sell on the max of the previus candle?

### Minimal, reproducible example

library(quantmod)
library(TTR)
library(data.table)
library(ggplot2)

getSymbols("EQTL3.sa", src = "yahoo" )
startdate <- as.Date("2019-01-01")
enddate <- as.Date("2022-01-01")

chartSeries(EQTL3.SA, TA=NULL)
addRSI(n= 2)
       
EQTL3.SA <- as.data.frame(EQTL3.SA)
ifr2 <- RSI(EQTL3.SA$EQTL3.SA.Open, n = 2)

TradeRule <- ifelse(ifr2$rsi < 25, 1, 0)

EQTL3.SA$compra <- TradeRule$rsi
[Insert sample data and code]
```

**Comment by joshuaulrich** [comment]
Take a look at my blog post, [RSI(2) with position sizing](https://blog.fosstrading.com/2009/05/rsi2-with-position-sizing.html).

I'm going to close this because it's not something that needs to be fixed. But feel free to continue the discussion.
