### ISSUE TITLE
StockCharts link is dead in ?MACD

### ISSUE THREAD

**Issue by anilca** [joshuaulrich/TTR#12]
Dead one:
http://stockcharts.com/education/IndicatorAnalysis/indic_MACD1.html

Active one:
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:moving_average_convergence_divergence_macd

**Comment by joshuaulrich** [comment]
Yes, as is the StockCharts link in `?OBV`.  Likely, all the StockCharts links are dead.
