### ISSUE TITLE
Issue on nSig for TRIX

### ISSUE THREAD

**Issue by SatoshiReport** [joshuaulrich/TTR#120]
The signal line does not recognize nSig *if* you do not list the maTypes used.  It uses n instead.

Here is the line of code:
signal <- do.call( maType, c( list(TRIX), list(n=n, ...) ) 

n should be nSig in this case.

**Comment by joshuaulrich** [comment]
Thanks for the report! Can you confirm that the example below illustrates the problem? The 'signal' for the current calculation matches `nSig_100` when it should match `nSig_9`.

```r
library(xts)
library(TTR)
data(ttrc)
x <- with(ttrc, xts(Close, Date))
trix  <- TRIX(x, n = 100)
trix$nSig_100 <- EMA(trix$TRIX, 100)
trix$nSig_9 <- EMA(trix$TRIX, 9)
tail(trix)
##                  TRIX     signal   nSig_100     nSig_9
## 2006-12-21 0.04825510 0.05648243 0.05648243 0.04588966
## 2006-12-22 0.04892560 0.05633279 0.05633279 0.04649685
## 2006-12-26 0.04959592 0.05619939 0.05619939 0.04711666
## 2006-12-27 0.05027224 0.05608202 0.05608202 0.04774778
## 2006-12-28 0.05095174 0.05598043 0.05598043 0.04838857
## 2006-12-29 0.05163177 0.05589432 0.05589432 0.04903721
```

**Comment by SatoshiReport** [comment]
Yes, that is a perfect example.
