### ISSUE TITLE
passing parameter for ADX (smoothing) calculation

### ISSUE THREAD

**Issue by openbmsjsc** [joshuaulrich/TTR#18]
In the code it seems that `n` for `ADX` calculation is the same as `n` for `DX` calculation.

``` r
maArgs <- list(n = n, ...)
```

Should we separate these 2? If we change here, we should probably change in `addADX` as well.

**Comment by joshuaulrich** [comment]
Can you please clarify? What do you want to separate, and why?

**Comment by openbmsjsc** [comment]
I think there are 2 parameters: DX period and Smoothing period (to calculate ADX, see https://www.linnsoft.com/techind/adx-avg-directional-movement, tab Preferences). Therefore setting up 2 separate parameters will give more controls for technical analysts. In particular, I'm trying to replicate this in R (Charles Schaap - Using ADX to Trade Breakouts, Pullbacks, and Reversal Patterns)

Of course we should default the smoothing to DX period as with present.

Thanks.

**Comment by openbmsjsc** [comment]
How should I submit a patch?

**Comment by joshuaulrich** [comment]
There's no bug in the `ATR` call. The `n` only matters for the average true range, but `ADX` only uses the raw true range from the `ATR` output.

Instead of your proposed patch, I think I would prefer a solution where the user could specify a separate `n` for the `ADX` via the `maType` argument. For example: `maType = list("EMA", n = 20)`.  See the `RSI` code for an example of how I've done this.

**Comment by openbmsjsc** [comment]
Thank you for the feedback. It's certainly better not to add another parameter. I'll look at the RSI code.

However, I thought `ATR(HLC)[,"tr"]` is the same as `ATR(HLC,=14)[,"tr"]` (from the ATR code), and hence it seems like a bug if a different n was passed to ADX call.

**Comment by openbmsjsc** [comment]
Another attempt. I'm still learning R so the code might not be optimal or R-styled.
I also make it consistent if wilder is not specified when maType='EMA'. **This seems to happen also in RSI, ATR, and maybe elsewhere.** Perhaps we should look at them as well?

Tests below are for the current version of ADX

```
> identical(TTR::ADX(ttrc[,c("High", "Low", "Close")], n=20),TTR::ADX(ttrc[,c("High", "Low", "Close")], n=20, maType="EMA", wilder=T))
[1] TRUE
> identical(TTR::ADX(ttrc[,c("High", "Low", "Close")], n=20),TTR::ADX(ttrc[,c("High", "Low", "Close")], n=20, maType="EMA"))
[1] FALSE

```

Thank you for feedback.

```
index cb42038..90224eb 100644
--- a/R/ADX.R
+++ b/R/ADX.R
@@ -93,6 +93,19 @@ function(HLC, n=14, maType, ...) {
     maArgs$wilder <- TRUE
   }
 
+  if (is.list(maType)) {
+    # If MA function has 'n' arg, see if it's populated in maType;
+    # if it isn't, populate it with ADX's formal 'n'
+    if (!is.null( formals(maType[[1]])$n ) && is.null(maType$n)) {
+      maType$n <- n
+    }
+    maArgs <- maType[-1]
+    maType <- maType[[1]]
+  }
+  if (maType == 'EMA' && is.null(maArgs$wilder)) {
+    maArgs$wilder <- TRUE
+  }
+
   ADX <- do.call( maType, c( list(DX), maArgs ) )
 
   result <- cbind( DIp, DIn, DX, ADX )

```

**Comment by openbmsjsc** [comment]
I just wonder if you would consider to merge this patch?

**Comment by ethanbsmith** [comment]
> I also make it consistent if wilder is not specified when maType='EMA'. **This seems to happen also in RSI, ATR, and maybe elsewhere.** Perhaps we should look at them as well?

the R language supports undefined parameter passing with `...` which in this case are passed to the ma function, so you can just pass those parameters to the `ATR` call. see difference in the `atr` column output below:
```r
> tail(ATR(HLC(getSymbols("SPY")), n = 20, maType = "EMA", wilder = T))
                tr      atr trueHigh  trueLow
2022-10-17 10.6991 8.890820 367.9799 357.2808
2022-10-18  8.6300 8.877779 375.4500 366.8200
2022-10-19  6.3000 8.748890 371.8500 365.5500
2022-10-20  8.0600 8.714445 372.6700 364.6100
2022-10-21 11.2600 8.841723 374.8000 363.5400
2022-10-24  6.9500 8.747137 380.0600 373.1100
> tail(ATR(HLC(getSymbols("SPY")), n = 20, maType = "EMA", wilder = F))
                tr      atr trueHigh  trueLow
2022-10-17 10.6991 9.701230 367.9799 357.2808
2022-10-18  8.6300 9.599208 375.4500 366.8200
2022-10-19  6.3000 9.284998 371.8500 365.5500
2022-10-20  8.0600 9.168331 372.6700 364.6100
2022-10-21 11.2600 9.367538 374.8000 363.5400
2022-10-24  6.9500 9.137296 380.0600 373.1100
```

i dont think there are any remaining issues here. just opportunities for documentation or possibly some refactoring

**Comment by allanggar** [comment]
+19GOOD +
