### ISSUE TITLE
package

### ISSUE THREAD

**Issue by rehmanasif** [joshuaulrich/TTR#20]
Error in library.dynam(lib, package, package.lib) : 
  DLL 'TTR' not found: maybe not installed for this architecture?
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/user/Documents/R/win-library/3.2/Accuracy'
* restoring previous 'C:/Users/user/Documents/R/win-library/3.2/Accuracy'

Exited with status 1.

**Comment by joshuaulrich** [comment]
What command produced that error? Is there a `traceback()`? What's the output from `sessionInfo()`?

**Comment by joshuaulrich** [comment]
Closing due to vagueness and lack of response from OP.
