### ISSUE TITLE
xts/zoo are not automatically imported when loading TTR 0.23-0 

### ISSUE THREAD

**Issue by hifin** [joshuaulrich/TTR#24]
I use R 3.1.2 and recently upgraded TTR from 0.22 to 0.23. However, now when I load TTR, xts/zoo are not automatically imported. Any clue? Thanks!

**Comment by joshuaulrich** [comment]
CRAN prefers that packages "Import" other packages, rather than "Depend" on them. This avoids cluttering the users's search path.
