### ISSUE TITLE
stockSymbols doesn't return IPOyear Sector Industry

### ISSUE THREAD

**Issue by eranzwilling** [joshuaulrich/TTR#35]
Hello, 

I'm running the function stockSymbols(), but opposed to previous runs, today I simply don't get the data of IPOyear, Sector and Industry. It all returns NA.

Thanks!
Eran

**Comment by eranzwilling** [comment]
sorry. Just tried to get this info from Nasdaq.com and it seems that the site itself doesn't provide it for some any reason. So I guess it's not an issue of this function. Why is it like that ?? no idea :(

**Comment by joshuaulrich** [comment]
To follow-up: I just checked, and there are now non-NA for IPOyear, Sector, and Industry.

**Comment by eranzwilling** [comment]
many thanks !
