### ISSUE TITLE
KDJ indicator in TTR

### ISSUE THREAD

**Issue by Shicheng-Guo** [joshuaulrich/TTR#48]
Relationship between Stochastic Oscillator and KDJ index
Stochastic Oscillator / Stochastic Momentum Index

Dear Joshua, 
It is quite interesting there is no KDJ indicator in TTR. Is there any possibility to add this KDJ lines to our new TTR version. 

https://docs.anychart.com/Stock_Charts/Technical_Indicators/KDJ

Thanks.

**Comment by joshuaulrich** [comment]
I [already explained](https://github.com/joshuaulrich/quantmod/issues/183#issuecomment-322089236) why there is no KDJ indicator in TTR in the [issue you opened in the quantmod repo](https://github.com/joshuaulrich/quantmod/issues/183):

> ...the only difference between the "KDJ" indicator and the stochastic oscillator is the addition of "the J line", which is described as the difference between %D and %K. This is something you can easily calculate using the output from the `stoch()` function. It's not clear to me that it warrants a completely new function.

Opening another issue will not change my mind (though it is a little annoying).
