### ISSUE TITLE
Errors in EMV and SNR

### ISSUE THREAD

**Issue by chenhuiyou** [joshuaulrich/TTR#49]
Hi, I found there are two errors in TTR:

1. EMV function returns two columns with names: 'emv' and 'maEMV'. But the documentation indicates the latter as 'emvMA'.

2. SNR has a bug in getting column by $:
`snr <- SNR(HLC, n=10)`
`Error in ATR(HLC, n, ...)$atr : $ operator is invalid for atomic vectors`

I might be using the dev version:
`packageVersion("TTR")`
`[1] ‘0.23.2’`

Thanks!

**Comment by joshuaulrich** [comment]
Thanks for the reports!  Both are now fixed.

**Comment by chenhuiyou** [comment]
Hi Joshuaulrich,

Is it possible to make column names more specific like Name+Period? For example, for moving average looking back 20 days, it returns 'SMA_20'. 

In general, people would compare different looking back periods. I have to rename them every time.

**Comment by braverock** [comment]
It is unlikely that we would change this in TTR, because a lot of external code expects behavior as it is right now.
many frameworks which use TTR (like quantstrat) allow labeling of indicator calculations to keep multiple related calcs such as your multiple lookback periods, separate.

**Comment by braverock** [comment]
it is also rather simple to do:
```r
x <- xts(rnorm(100),as.Date(1:100)
colnames(x) <- 'fake_ret'
x$SMA_20    <- SMA(x,20)
```
