### ISSUE TITLE
Feature request: Please add the Hurst Index to the list of provided indicators

### ISSUE THREAD

**Issue by sillasgonzaga** [joshuaulrich/TTR#64]
Hurst Index is quite ofted used as a measurement of trend strength for financial time series.

**Comment by braverock** [comment]
The Hurst Index is already in PerformanceAnalytics.  It is there rather than TTR because it is a return-based metric, not a price-based metric.

There are also many many variants of the Hurst regression coefficient in other R packages.

I don't see any reason to replicate it in TTR.

**Comment by sillasgonzaga** [comment]
Thanks for the reply.
