### ISSUE TITLE
stoch:  lower bound incorrect with bounded=FALSE

### ISSUE THREAD

**Issue by rfinfun** [joshuaulrich/TTR#74]
Hi Joshua,  In: https://github.com/joshuaulrich/TTR/blob/master/R/stochastics.R

Line 152ff: 

```r
  if(bounded) {
    hmax <- runMax(high, nFastK)
    lmin <- runMin( low, nFastK)
  } else {
    hmax <- runMax(c(high[1],high[-NROW(HLC)]), nFastK)
    lmin <- runMax(c( low[1], low[-NROW(HLC)]), nFastK)  #  this is the line!!!
  }
```
It should be
```r
    lmin <- runMin(c( low[1], low[-NROW(HLC)]), nFastK)  #  this is the line!!!
```
I stumbled over this just by looking at the code.  No testing was performed. 
Thanks for the great package.  I just started studying it.  

Regards, A.

**Comment by joshuaulrich** [comment]
Yep, this is certainly a bug. Ugh. Sorry it took me so long to address it!
