### ISSUE TITLE
stockSymbols points to broken link

### ISSUE THREAD

**Issue by Javdat** [joshuaulrich/TTR#83]
After nasdaq website re-design `stockSymbols()` is broken. It points to https://www.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange=NASDAQ&render=download which doesn't exist anymore. 

New screener seems to be located at: https://www.nasdaq.com/market-activity/stocks/screener

But it doesn't seem to have screening by exchanges.

```r
> library(TTR)
> stockSymbols("NASDAQ")
Fetching NASDAQ symbols...
Error in file(file, "rt") : 
  cannot open the connection to 'http://www.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange=NASDAQ&render=download'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'https://www.nasdaq.com/screening/companies-by-name.aspx?letter=0&exchange=NASDAQ&render=download': HTTP status was '404 Not Found'
```

**Comment by joshuaulrich** [comment]
Thanks for the report!  I will look into the best way to fix this.

**Comment by dcmg21** [comment]
I can't download all symbols anymore.  I get the error Error in names(x) <- value : 
  'names' attribute [8] must be the same length as the vector [1].  Is this all related?  When will it be fixed?

**Comment by joshuaulrich** [comment]
@dcmg21 Yes, that's related to this issue.  It's fixed now and will be on CRAN soon.

**Comment by joshuaulrich** [comment]
@Javdat thanks again for this report! A patched version is on CRAN now.  Windows binaries should be available in a few days.

**Comment by qedtec** [comment]
Hi Joshua,
I'm getting NA fields

```
> packageVersion("TTR")
[1] ‘0.24.2’
> x <- TTR::stockSymbols()
Fetching NASDAQ symbols...
Fetching non-NASDAQ symbols...
> table(x$Sector)
< table of extent 0 >
```

**Comment by joshuaulrich** [comment]
@qedtec that's expected. See the [commit message](https://github.com/joshuaulrich/TTR/commit/2199dd838aa7ff62291da9fb30ae3ee76c5ac446):

> **Use NASDAQ FTP to get stock symbols**
> 
> Users have been getting timeout issues and errors using the URL:
> https://old.nasdaq.com/screening/companies-by-name.aspx
> 
> Switch to the FTP URL: ftp://ftp.nasdaqtrader.com/SymbolDirectory/.
> 
> *Keep the column names from the old data set, but set all the values
> to NA.* Also keep the columns in the same order, and append the new
> columns to the end of the output.

Several of the columns from the original data set are no longer available in the FTP file. I will add a note to the documentation to communicate this better to users.

**Comment by joshuaulrich** [comment]
@qedtec I added a note in https://github.com/joshuaulrich/TTR/commit/4ca5567499897462c5c49cee8249a908903491a1. It will be in the next release.
