### ISSUE TITLE
StockSymbols() errors out

### ISSUE THREAD

**Issue by dcmg21** [joshuaulrich/TTR#84]
### Description

Error in names(x) <- value : 
  'names' attribute [8] must be the same length as the vector [1]

### Expected behavior

I used to be able to download these without issue and now have the error below.

### Minimal, reproducible example

```r
[Insert sample data and code]
```

### Session Info

```r
[Insert your sessionInfo() output]
```

**Comment by joshuaulrich** [comment]
Please help me keep relevant information about issues in one place.  Creating multiple issues for the same bug creates noise and more work for me.
