### ISSUE TITLE
stockSymbols no longer working

### ISSUE THREAD

**Issue by phakedoctor** [joshuaulrich/TTR#85]
### Description

stockSymbols is throwing an error that it never has before. I didn't change my code...

### Expected behavior

Typically, this stores all symbols from the NASDAQ and NYSE into AllSym, but now it returns the error.

### Minimal, reproducible example

AllSym <- stockSymbols(exchange = c("NASDAQ", "NYSE"), sort.by = c("Exchange","Symbol"))

### Session Info

> AllSym <- stockSymbols(exchange = c("NASDAQ", "NYSE"), sort.by = c("Exchange","Symbol"))
Fetching NASDAQ symbols...
Error in names(x) <- value : 
  'names' attribute [8] must be the same length as the vector [1]
>

**Comment by joshuaulrich** [comment]
This is a duplicate of #83. You didn't provide your `sessionInfo()` output, so I assume you haven't upgraded to the newest version on CRAN.  Please upgrade to get the fixed version.

**Comment by phakedoctor** [comment]
Thank you, Joshua, you are correct. I thought that I had fully updated but was wrong – sorry to bother you with this. Thank you very much for this package – I use it often and am really impressed with the functionality.
