### ISSUE TITLE
volatility

### ISSUE THREAD

**Issue by AavMarcus1** [joshuaulrich/TTR#91]
TTR/Volatility with data from AlphaVantage

```r
GSPC <- getSymbols("^GSPC", src="av", output.size="full", auto.assign=FALSE)
volatility(GSPC, n=30,calc="close",N=252)
...
2020-04-14 0.85666235
2020-04-15 0.84827964
2020-04-16 0.84356123
```
If i do a manual calculation i get the desired result, same results as displayed on https://www.ivolatility.com/options/SPX/0 per 2020-04-16 is 83.40%.
```r
rGSPC =diff(log(GSPC[,4]))
sd(last(rGSPC,30))*sqrt(252)
0.8340144

```
Maybe it's the n-2 instead of n-1 periods ?

**Comment by quantumcumque** [comment]
Never mind, you can just delete or close.
